# configure start
# Sigmoid AM

trainer:
  checkpoint: "./tune/2spk_pit_b"
  optimizer: "adam"
  # 1e-3 => str
  # 1.0e-3 => float
  lr: 1.0e-3
  momentum: 0.8
  weight_decay: 0
  clip_norm: 200
  min_lr: 1.0e-10
  patience: 1
  factor: 0.7

model:
  num_spks: 2
  rnn: "lstm"
  num_layers: 3
  hidden_size: 896
  dropout: 0.5
  non_linear: "sigmoid"
  bidirectional: true

spectrogram_reader:
  frame_shift: 128
  frame_length: 256
  window: "hann"
  transpose: true
  # NOTE: do not apply log here
  # false => produce psm
  # true  => produce irm
  apply_abs: true

train_scp_conf:
  mixture: "./conf/2spk/simple30/train/mix.scp"
  spk1: "./conf/2spk/simple30/train/spk1.scp"
  spk2: "./conf/2spk/simple30/train/spk2.scp"

valid_scp_conf:
  mixture: "./conf/2spk/simple30/dev/mix.scp"
  spk1: "./conf/2spk/simple30/dev/spk1.scp"
  spk2: "./conf/2spk/simple30/dev/spk2.scp"

debug_scp_conf:
  mixture: "./conf/2spk/simple30/mix.scp"
  spk1: "./conf/2spk/simple30/spk1.scp"
  spk2: "./conf/2spk/simple30/spk2.scp"

dataloader:
  shuffle: true
  batch_size: 8
  drop_last: false
  mvn_dict: "./conf/2spk/simple30/cmvn.dict"
